### ISSUE TITLE
Add exception handling to `create` view

### ISSUE THREAD

**Issue by chigby** [wagtail/wagtail-autocomplete#134]
When delegating object creation to a model's `autocomplete_create` method, sometimes an exception will be raised. In that case, we might want to handle the exception and return a `4xx` response rather than a `500`. 

This is the part of the code that potentially causes a `500`:

https://github.com/wagtail/wagtail-autocomplete/blob/3ae8cf77bb4d42bba7eb310ddae2a7bf302ac850/wagtailautocomplete/views.py#L105

**Comment by chigby** [comment]
Example of a traceback of this occurring on one of our sites:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "incident_charge_title_key"
DETAIL:  Key (title)=(unknown) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/wagtail/admin/auth.py", line 184, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/wagtailautocomplete/views.py", line 109, in create
    instance = method(value)
  File "/django/incident/models/items.py", line 94, in autocomplete_create
    return kls.objects.create(title=value)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/site-packages/modelcluster/models.py", line 201, in save
    super().save(update_fields=real_update_fields, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "incident_charge_title_key"
DETAIL:  Key (title)=(unknown) already exists.
```

via [this log entry](https://logs.freedom.press/app/discover#/doc/filebeat-*/filebeat-gke-2023.09.01?id=BnNFUYoBs2CcqTNHbtGY) (not publicly accessible)

**Comment by chigby** [comment]
What do people think about returning a 409 status code in the case of an `IntegrityError`?

> [6.5.8](https://www.rfc-editor.org/rfc/rfc7231#section-6.5.8).  409 Conflict
> The 409 (Conflict) status code indicates that the request could not
   be completed due to a conflict with the current state of the target
   resource.  This code is used in situations where the user might be
   able to resolve the conflict and resubmit the request.  The server
   SHOULD generate a payload that includes enough information for a user
   to recognize the source of the conflict.

 > Conflicts are most likely to occur in response to a PUT request.  For
   example, if versioning were being used and the representation being
   PUT included changes to a resource that conflict with those made by
   an earlier (third-party) request, the origin server might use a 409
   response to indicate that it can't complete the request.  In this
   case, the response representation would likely contain information
   useful for merging the differences based on the revision history.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

**Comment by chigby** [comment]
Thinking more about this, I'd feel a little better about having wagtail-autocomplete's view catch Django's generic `ValidationError` (returning a 400 status if so), and leaving it up to the user's model to catch more specific DB or business logic errors (such as `IntegrityError`) on its own.
